controller_manager:
  ros__parameters:
    update_rate: 1  # Hz Reduced from 10Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - r_shoulder_swing_joint
      - l_shoulder_swing_joint
      - r_shoulder_lateral_joint
      - l_shoulder_lateral_joint
      - r_elbow_joint
      - l_elbow_joint
      - r_hip_twist_joint
      - l_hip_twist_joint
      - r_hip_lateral_joint
      - l_hip_lateral_joint
      - r_hip_swing_joint
      - l_hip_swing_joint
      - r_knee_joint
      - l_knee_joint
      - r_ankle_swing_joint
      - l_ankle_swing_joint
      - r_ankle_lateral_joint
      - l_ankle_lateral_joint
    allow_partial_joints: true
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
